---
vim_clone_path: "{{ ansible_user_dir }}/vim"
vim_dotfiles: []
vim_extra_features: []
vim_install_prefix: "/usr/local"
vim_plugin_autoremove: false
vim_plugin_autoupdate: false
vim_plugin_install: []
vim_plugin_manager: "native"
vim_plugin_native_dir: "{{ ansible_user_dir }}/.vim/pack/plugins"
vim_version: ""

