---
- name: Ensure package dependencies
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vim_extra_packages }}"

- name: Install vim from source
  ansible.builtin.include_tasks: "vim-install.yml"
  when: vim_version

- name: Copy dotfiles in place
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item | basename }}"
  with_items: "{{ vim_dotfiles }}"

- name: Apply native plugin manager
  ansible.builtin.include_tasks: "vim-native.yml"
  when:
    - vim_plugin_manager ==  "native"
    - vim_plugin_install | length > 0

- name: Apply vim-plug plugin manager
  ansible.builtin.include_tasks: "vim-plug.yml"
  when: vim_plugin_manager == "vim-plug"

