---
- name: Ensure autoload directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.vim/autoload"
    state: directory

- name: Ensure vim-plug is installed
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_user_dir }}/.vim/autoload/plug.vim"

- name: Install plugins
  ansible.builtin.command: "vim -es -u {{ ansible_user_dir }}/.vimrc -i NONE -c PlugInstall -c qa"

- name: Update plugins
  ansible.builtin.command: "vim -es -u {{ ansible_user_dir }}/.vimrc -i NONE -c PlugUpdate -c qa"
  when: vim_plugin_autoupdate

- name: Remove unused plugins
  ansible.builtin.command: "vim -es -u {{ ansible_user_dir }}/.vimrc -i NONE -c PlugClean! -c qa"
  register: remove
  when: vim_plugin_autoremove

