---
dependency:
  name: shell
  command: >
    rm -rf galaxy.yml && rm -rf fixture/ \
    && sh scripts/galaxy.sh -v 1.0.0 \
    && mkdir -p fixture/ansible_collections \
    && ansible-galaxy collection build \
         --force \
         --output-path fixture \
    && ansible-galaxy collection install \
         --force \
         -p fixture/ansible_collections \
         fixture/orjangj-editors-1.0.0.tar.gz
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2004}-ansible
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: True
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  env:
    ANSIBLE_COLLECTIONS_PATH: "$MOLECULE_PROJECT_DIRECTORY/fixture/ansible_collections"
scenario:
  name: vim
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    #- idempotence
    - verify
    - destroy
verifier:
  name: ansible
  directory: tests

