---
- name: Install neovim from releases
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.deb"
  when:
    - ansible_facts['os_family'] == "Debian"
    - neovim_version

- name: Ensure neovim configuration directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Copy configs in place
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/nvim/{{ item | basename }}"
  with_items: "{{ neovim_configs }}"

- name: Ensure package dependencies
  become: true
  ansible.builtin.package:
    name: "{{ neovim_packages }}"

- name: Apply vim-plug plugin manager
  ansible.builtin.include_tasks: "vim-plug.yml"
  when: neovim_plugin_manager == "vim-plug"

