---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'orjangj.editors'

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu2004
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'orjangj.editors'

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests
        run: molecule test --all
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ matrix.image }}
